### ISSUE TITLE
Feature request: add RouterToken registration API

### ISSUE THREAD

**Issue by KevinGrandon** [fusionjs/fusion-plugin-react-router#113]
### Type of issue

Teams would like to be able to access the `history` object that we use in this plugin for various use cases. One of them being syncing state to redux in https://github.com/ReactTraining/react-router/tree/master/packages/react-router-redux

### Description

Add a `RouterToken` which we can use as a dependency to get access to history.
```
createPlugin({
  RouterToken: router
}, ({router}) => {
  // Will I be able to do this?
  router.from(ctx).history
```

**Comment by alxmyth** [comment]
Closing this issue as resolved as of https://github.com/fusionjs/fusion-plugin-react-router/pull/168.

See the [RouterToken docs](https://github.com/fusionjs/fusion-plugin-react-router#routertoken) for more details.
