### ISSUE TITLE
Unable to use `render` prop for `Route`

### ISSUE THREAD

**Issue by brendean** [fusionjs/fusion-plugin-react-router#121]
### Type of issue
Feature request

### Description
The `render` prop is the [suggested approach](https://github.com/ReactTraining/react-router/issues/5521) for passing props to a `Route` from a parent component but `fusion-plugin-react-router` does not allow this property.

### Current behavior
When passing the prop `render` to the `Route` component an error is thrown `'Cannot pass render function to tracking route'`. 

### Expected behavior
Should be able to pass `render` to a `Route`

### Your environment

* fusion-plugin-react-router version: 1.0.4

**Comment by brendean** [comment]
I was able to side step this issue by importing `Route` directly from `react-router` but seems like functionality fusion may want to support

**Comment by KevinGrandon** [comment]
It looks like this was actually fixed in: https://github.com/fusionjs/fusion-plugin-react-router/pull/132
